version: "3"
services:
  rippled:
    build: .
    ports:
      - "51235:51235"
      - "5005:5005"
      - "5006:5006"
    volumes:
      - "~/.local/share/rippled/docker/:/data"
      - "./rippled.conf:/etc/rippled.conf"
    command: --conf /etc/rippled.conf